// 只在宿主冻结审批目标后使用；模型不能提供 SQL、角色 ID 或待写字段。
export function userCreationProgram(payload: string): string {
  return [
    "import base64,hashlib,json,re,sys,uuid",
    "connection=None",
    "try:",
    " import pymysql",
    ` payload=json.loads(base64.b64decode(${JSON.stringify(payload)}).decode('utf-8'))`,
    " roles={'YY_YH':'ROLE_YY','KF_YH':'ROLE_KF','CW_YH':'ROLE_CW'}",
    " kind=payload.get('createUserType'); username=payload.get('username',''); source=payload.get('whitelistSourceUsername','')",
    " if kind not in roles or payload.get('mode') not in ('inspect_create','create'): raise ValueError('invalid creation')",
    " if not re.fullmatch(r'[a-z0-9_.@+\\-]{1,80}',username) or username=='admin' or not re.fullmatch(r'[A-Za-z0-9_.@+\\-]{1,120}',source) or source.lower()==username: raise ValueError('invalid target')",
    " connection=pymysql.connect(host=payload['host'],port=int(payload['port']),user=payload['databaseUsername'],password=payload['databasePassword'],database=payload['database'],charset='utf8mb4',connect_timeout=8,read_timeout=20,write_timeout=20,autocommit=False,cursorclass=pymysql.cursors.DictCursor)",
    " with connection.cursor() as cursor:",
    "  suffix=' FOR UPDATE' if payload['mode']=='create' else ''",
    "  cursor.execute('SELECT id FROM sys_user WHERE username=%s OR id=%s LIMIT 2'+suffix,(username,username))",
    "  existing=cursor.fetchall()",
    "  cursor.execute('SELECT id,username,user_type,status,del_flag,ip_white_list FROM sys_user WHERE username=%s LIMIT 2'+suffix,(source,))",
    "  templates=cursor.fetchall()",
    "  cursor.execute('SELECT id,role_code,role_name FROM sys_role WHERE role_code=%s LIMIT 2'+suffix,(roles[kind],))",
    "  role_rows=cursor.fetchall()",
    "  role_id=role_rows[0]['id'] if len(role_rows)==1 else None",
    "  cursor.execute('SELECT role_id,permission_id,data_rule_ids FROM sys_role_permission WHERE role_id=%s ORDER BY id LIMIT 2001'+suffix,(role_id,))",
    "  permissions=cursor.fetchall()",
    "  if existing: result={'ok':False,'resultCode':'already_exists'}",
    "  elif len(templates)!=1: result={'ok':False,'resultCode':'invalid_whitelist_source'}",
    "  elif len(role_rows)!=1 or not permissions or len(permissions)>2000: result={'ok':False,'resultCode':'invalid_creation_role'}",
    "  else:",
    "   template=templates[0]; whitelist=str(template.get('ip_white_list') or '')",
    "   if str(template.get('username') or '')!=source or template.get('user_type')!=kind or template.get('del_flag')!=0 or template.get('status')!=1 or str(template.get('username') or '').lower()=='admin': result={'ok':False,'resultCode':'invalid_whitelist_source'}",
    "   elif not re.fullmatch(r'AESGCM1:[A-Za-z0-9_\\-]{39,4096}',whitelist): result={'ok':False,'resultCode':'invalid_whitelist_source'}",
    "   else:",
    "    token=hashlib.sha256(json.dumps([username,kind,template,role_rows,permissions],ensure_ascii=False,sort_keys=True,separators=(',',':'),default=str).encode('utf-8')).hexdigest()",
    "    if payload['mode']=='inspect_create': result={'ok':True,'resultCode':'eligible','sysUserId':username,'stateToken':token,'userType':kind,'status':1,'delFlag':0}",
    "    elif payload.get('sysUserId')!=username or payload.get('stateToken')!=token: result={'ok':False,'resultCode':'conflict'}",
    "    else:",
    "     password=str(payload.get('passwordHash') or ''); salt=str(payload.get('passwordSalt') or ''); totp=str(payload.get('totpSecret') or '')",
    "     if not re.fullmatch(r'[a-f0-9]+',password) or len(password)%16 or not re.fullmatch(r'[A-Za-z0-9]{8}',salt) or not re.fullmatch(r'[A-Z2-7]{32}',totp): raise ValueError('invalid material')",
    "     cursor.execute('INSERT INTO sys_user (id,username,realname,password,salt,totp,user_type,parent_id,status,del_flag,first_login_flag,ip_white_list,create_by,update_by,create_time,update_time) VALUES (%s,%s,%s,%s,%s,%s,%s,NULL,1,0,1,%s,%s,%s,NOW(),NOW())',(username,username,username,password,salt,totp,kind,whitelist,'telegram_ai','telegram_ai'))",
    "     if cursor.rowcount!=1: raise ValueError('unexpected insert count')",
    "     link_id=uuid.uuid4().hex",
    "     cursor.execute('INSERT INTO sys_user_role (id,user_id,role_id) VALUES (%s,%s,%s)',(link_id,username,role_id))",
    "     if cursor.rowcount!=1: raise ValueError('unexpected role count')",
    "     cursor.execute('SELECT id,username,password,salt,totp,user_type,parent_id,status,del_flag,first_login_flag,ip_white_list FROM sys_user WHERE id=%s',(username,))",
    "     row=cursor.fetchone()",
    "     cursor.execute('SELECT role_id FROM sys_user_role WHERE user_id=%s LIMIT 2',(username,)); links=cursor.fetchall()",
    "     verified=bool(row) and row['id']==username and row['username']==username and row['user_type']==kind and row['status']==1 and row['del_flag']==0 and row['first_login_flag']==1 and row['parent_id'] is None and row['password']==password and row['salt']==salt and row['totp']==totp and row['ip_white_list']==whitelist and len(links)==1 and links[0]['role_id']==role_id",
    "     result={'ok':verified,'resultCode':'created' if verified else 'verification_failed','sysUserId':username,'userType':kind,'passwordReset':True,'totpReset':True}",
    " if result.get('resultCode')=='created': connection.commit()",
    " else: connection.rollback()",
    " print(json.dumps(result,ensure_ascii=False))",
    "except Exception as error:",
    " if connection:",
    "  try: connection.rollback()",
    "  except Exception: pass",
    " print(json.dumps({'ok':False,'resultCode':'database_error','errorType':type(error).__name__}))",
    " sys.exit(1)",
    "finally:",
    " if connection:",
    "  try: connection.close()",
    "  except Exception: pass",
  ].join("\n")
}
